[versions]
kotlin = "2.1.21"
kotlinx-coroutines = "1.10.2"
open-feature-kotlin-sdk = "0.4.1"

[libraries]
openfeature-kotlin-sdk = { group="dev.openfeature", name="kotlin-sdk", version.ref="open-feature-kotlin-sdk" }
kotlin-test = { group="org.jetbrains.kotlin", name="kotlin-test", version.ref="kotlin" }
kotlinx-coroutines-core = { group="org.jetbrains.kotlinx", name="kotlinx-coroutines-core", version.ref="kotlinx-coroutines" }
kotlinx-coroutines-test = { group="org.jetbrains.kotlinx", name="kotlinx-coroutines-test", version.ref="kotlinx-coroutines" }

[plugins]
kotlin-multiplatform = { id="org.jetbrains.kotlin.multiplatform", version.ref="kotlin" }
kotlinx-atomicfu = { id="org.jetbrains.kotlinx.atomicfu", version="0.27.0" }
ktlint = { id="org.jlleitschuh.gradle.ktlint", version="12.3.0" }
nexus-publish = { id="io.github.gradle-nexus.publish-plugin", version="2.0.0" }
binary-compatibility-validator = { id="org.jetbrains.kotlinx.binary-compatibility-validator", version="0.17.0" }